// SPDX-License-Identifier: MIT
// Copyright (C) 2026 go-hamqtt authors.

// Command genfields generates discovery/gen_fields.go: one struct per MQTT
// platform carrying the discovery keys that platform accepts and [Component]
// does not already declare.
//
// Typing these by hand is how the reference implementations ended up
// publishing keys Home Assistant drops in silence. The catalog knows the exact
// key set per platform, so the structs are derived from it and a platform that
// gains a key in a Home Assistant release gains a field on the next
// regeneration rather than on the next bug report.
//
// Usage: go run ./script/genfields
package main

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"reflect"
	"sort"
	"strings"

	hacatalog "github.com/SukramJ/go-ha-catalog"
)

// structural keys belong to the bundle or to the component's own discriminator,
// never to a platform's field set.
var structural = map[string]bool{"device": true, "origin": true, "platform": true}

// initialisms are the segments Go spells in caps.
var initialisms = map[string]string{
	"id": "ID", "url": "URL", "json": "JSON", "qos": "QoS", "rgb": "RGB",
	"rgbw": "RGBW", "rgbww": "RGBWW", "hs": "HS", "xy": "XY", "ip": "IP",
	"uid": "UID", "cct": "CCT", "hvac": "HVAC", "gpm": "GPM", "ct": "CT",
}

func main() {
	if err := run(); err != nil {
		fmt.Fprintln(os.Stderr, "genfields:", err)
		os.Exit(1)
	}
}

func run() error {
	owned, err := componentKeys("discovery/bundle.go")
	if err != nil {
		return err
	}
	mqtt, err := hacatalog.LoadMQTT()
	if err != nil {
		return err
	}

	type target struct {
		name     string // Go type name without the Fields suffix
		platform string
		variant  string
		keys     map[string]hacatalog.SchemaKey
	}
	var targets []target
	for _, platform := range sortedKeys(mqtt.Platforms) {
		schema := mqtt.Platforms[platform]
		if len(schema.Variants) == 0 {
			targets = append(targets, target{name: goName(platform), platform: platform, keys: schema.Keys})
			continue
		}
		for _, v := range sortedKeys(schema.Variants) {
			targets = append(targets, target{
				name:     goName(platform) + goName(v),
				platform: platform,
				variant:  v,
				keys:     schema.Variants[v].Keys,
			})
		}
	}

	var buf bytes.Buffer
	fmt.Fprintf(&buf, `// SPDX-License-Identifier: MIT
// Copyright (C) 2026 go-hamqtt authors.

// Code generated by script/genfields. DO NOT EDIT.
//
// Generated from go-ha-catalog snapshot %s (%s).

package discovery

`, hacatalog.SnapshotVersion, hacatalog.SnapshotRef)

	var empty []string
	var index [][2]string // catalog key -> Go type name
	for _, t := range targets {
		var keys []string
		for k := range t.keys {
			if owned[k] || structural[k] {
				continue
			}
			keys = append(keys, k)
		}
		if len(keys) == 0 {
			empty = append(empty, t.platform)
			continue
		}
		sort.Strings(keys)
		catalogKey := t.platform
		if t.variant != "" {
			catalogKey += "/" + t.variant
		}
		index = append(index, [2]string{catalogKey, t.name + "Fields"})

		what := "platform " + t.platform
		if t.variant != "" {
			what += " (schema " + t.variant + ")"
		}
		fmt.Fprintf(&buf, "// %sFields are the discovery keys %s accepts beyond the ones\n"+
			"// [Component] already carries.\ntype %sFields struct {\n", t.name, what, t.name)
		for _, k := range keys {
			req := ""
			if t.keys[k].Required {
				req = " // required"
			}
			fmt.Fprintf(&buf, "\t%s %s `json:\"%s,omitempty\"`%s\n", goName(k), goType(t.keys[k]), k, req)
		}
		buf.WriteString("}\n\n")
	}

	buf.WriteString(`// FieldsIndex maps a platform — "<platform>", or "<platform>/<variant>" for
// the two platforms that dispatch on a payload key — to a zero value of the
// Fields struct carrying that platform's own discovery keys.
//
// It exists so nothing has to hand-maintain a switch from a platform to its
// struct: this package's validating test walks it, and a consumer can use it
// to find the type it should be filling in.
var FieldsIndex = map[string]any{
`)
	for _, e := range index {
		fmt.Fprintf(&buf, "\t%q: %s{},\n", e[0], e[1])
	}
	buf.WriteString("}\n\n")

	if len(empty) > 0 {
		fmt.Fprintf(&buf, "// No Fields struct is generated for %s: every key those\n"+
			"// platforms accept is already declared on [Component].\n",
			strings.Join(empty, ", "))
	}

	return os.WriteFile("discovery/gen_fields.go", buf.Bytes(), 0o600)
}

// goType picks the Go type from the catalog's record of what the key's
// Home Assistant validator accepts.
//
// The numeric and boolean types are pointers so a legitimate zero — a minimum
// of 0, an explicit false — survives `omitempty`, which would otherwise drop
// exactly the value the consumer meant to set.
func goType(entry hacatalog.SchemaKey) string {
	switch entry.Type {
	case "bool":
		return "*bool"
	case "int":
		return "*int"
	case "float":
		return "*float64"
	case "list":
		return "[]string"
	case "str":
		return "string"
	}
	// The validator named no type: a bare vol.Range, a whitelist, a custom
	// callable. Fall back to what the schema's own default reveals, then to a
	// string — the type every MQTT payload key ultimately is.
	switch entry.Default.(type) {
	case bool:
		return "*bool"
	case []any:
		return "[]string"
	}
	return "string"
}

func goName(snake string) string {
	var b strings.Builder
	for _, part := range strings.Split(snake, "_") {
		if part == "" {
			continue
		}
		if up, ok := initialisms[part]; ok {
			b.WriteString(up)
			continue
		}
		b.WriteString(strings.ToUpper(part[:1]) + part[1:])
	}
	return b.String()
}

// componentKeys reads the JSON tags off the hand-written Component struct.
//
// Parsing the source rather than reflecting over the type keeps the generator
// runnable when the generated file it writes does not compile — which is
// exactly the moment it needs to run.
func componentKeys(path string) (map[string]bool, error) {
	fset := token.NewFileSet()
	file, err := parser.ParseFile(fset, path, nil, 0)
	if err != nil {
		return nil, err
	}
	out := map[string]bool{}
	ast.Inspect(file, func(n ast.Node) bool {
		ts, ok := n.(*ast.TypeSpec)
		if !ok || ts.Name.Name != "Component" {
			return true
		}
		st, ok := ts.Type.(*ast.StructType)
		if !ok {
			return false
		}
		for _, f := range st.Fields.List {
			if f.Tag == nil {
				continue
			}
			tag := reflect.StructTag(strings.Trim(f.Tag.Value, "`")).Get("json")
			name, _, _ := strings.Cut(tag, ",")
			if name != "" && name != "-" {
				out[name] = true
			}
		}
		return false
	})
	if len(out) == 0 {
		return nil, fmt.Errorf("no Component struct found in %s", path)
	}
	return out, nil
}

func sortedKeys[V any](m map[string]V) []string {
	out := make([]string, 0, len(m))
	for k := range m {
		out = append(out, k)
	}
	sort.Strings(out)
	return out
}
