// SPDX-License-Identifier: MIT
// Copyright (C) 2026 go-hamqtt authors.

// Code generated by script/genfields. DO NOT EDIT.
//
// Generated from go-ha-catalog snapshot 2026.9.1 (2026.9.0b9-31-g76ca483aec0).

package discovery

// AlarmControlPanelFields are the discovery keys platform alarm_control_panel accepts beyond the ones
// [Component] already carries.
type AlarmControlPanelFields struct {
	Code                   string   `json:"code,omitempty"`
	CodeArmRequired        *bool    `json:"code_arm_required,omitempty"`
	CodeDisarmRequired     *bool    `json:"code_disarm_required,omitempty"`
	CodeTriggerRequired    *bool    `json:"code_trigger_required,omitempty"`
	PayloadArmAway         string   `json:"payload_arm_away,omitempty"`
	PayloadArmCustomBypass string   `json:"payload_arm_custom_bypass,omitempty"`
	PayloadArmHome         string   `json:"payload_arm_home,omitempty"`
	PayloadArmNight        string   `json:"payload_arm_night,omitempty"`
	PayloadArmVacation     string   `json:"payload_arm_vacation,omitempty"`
	PayloadDisarm          string   `json:"payload_disarm,omitempty"`
	PayloadTrigger         string   `json:"payload_trigger,omitempty"`
	SupportedFeatures      []string `json:"supported_features,omitempty"`
}

// BinarySensorFields are the discovery keys platform binary_sensor accepts beyond the ones
// [Component] already carries.
type BinarySensorFields struct {
	ExpireAfter *int   `json:"expire_after,omitempty"`
	ForceUpdate *bool  `json:"force_update,omitempty"`
	OffDelay    *int   `json:"off_delay,omitempty"`
	PayloadOff  string `json:"payload_off,omitempty"`
	PayloadOn   string `json:"payload_on,omitempty"`
}

// ButtonFields are the discovery keys platform button accepts beyond the ones
// [Component] already carries.
type ButtonFields struct {
	PayloadPress string `json:"payload_press,omitempty"`
}

// CameraFields are the discovery keys platform camera accepts beyond the ones
// [Component] already carries.
type CameraFields struct {
	ImageEncoding string `json:"image_encoding,omitempty"`
	Topic         string `json:"topic,omitempty"` // required
}

// ClimateFields are the discovery keys platform climate accepts beyond the ones
// [Component] already carries.
type ClimateFields struct {
	ActionTemplate                     string   `json:"action_template,omitempty"`
	ActionTopic                        string   `json:"action_topic,omitempty"`
	CurrentHumidityTemplate            string   `json:"current_humidity_template,omitempty"`
	CurrentHumidityTopic               string   `json:"current_humidity_topic,omitempty"`
	CurrentTemperatureTemplate         string   `json:"current_temperature_template,omitempty"`
	CurrentTemperatureTopic            string   `json:"current_temperature_topic,omitempty"`
	FanModeCommandTemplate             string   `json:"fan_mode_command_template,omitempty"`
	FanModeCommandTopic                string   `json:"fan_mode_command_topic,omitempty"`
	FanModeStateTemplate               string   `json:"fan_mode_state_template,omitempty"`
	FanModeStateTopic                  string   `json:"fan_mode_state_topic,omitempty"`
	FanModes                           []string `json:"fan_modes,omitempty"`
	Initial                            *float64 `json:"initial,omitempty"`
	MaxHumidity                        *float64 `json:"max_humidity,omitempty"`
	MaxTemp                            *float64 `json:"max_temp,omitempty"`
	MinHumidity                        *float64 `json:"min_humidity,omitempty"`
	MinTemp                            *float64 `json:"min_temp,omitempty"`
	ModeCommandTemplate                string   `json:"mode_command_template,omitempty"`
	ModeCommandTopic                   string   `json:"mode_command_topic,omitempty"`
	ModeStateTemplate                  string   `json:"mode_state_template,omitempty"`
	ModeStateTopic                     string   `json:"mode_state_topic,omitempty"`
	Modes                              []string `json:"modes,omitempty"`
	PayloadOff                         string   `json:"payload_off,omitempty"`
	PayloadOn                          string   `json:"payload_on,omitempty"`
	PowerCommandTemplate               string   `json:"power_command_template,omitempty"`
	PowerCommandTopic                  string   `json:"power_command_topic,omitempty"`
	Precision                          *float64 `json:"precision,omitempty"`
	PresetModeCommandTemplate          string   `json:"preset_mode_command_template,omitempty"`
	PresetModeCommandTopic             string   `json:"preset_mode_command_topic,omitempty"`
	PresetModeStateTopic               string   `json:"preset_mode_state_topic,omitempty"`
	PresetModeValueTemplate            string   `json:"preset_mode_value_template,omitempty"`
	PresetModes                        []string `json:"preset_modes,omitempty"`
	SwingHorizontalModeCommandTemplate string   `json:"swing_horizontal_mode_command_template,omitempty"`
	SwingHorizontalModeCommandTopic    string   `json:"swing_horizontal_mode_command_topic,omitempty"`
	SwingHorizontalModeStateTemplate   string   `json:"swing_horizontal_mode_state_template,omitempty"`
	SwingHorizontalModeStateTopic      string   `json:"swing_horizontal_mode_state_topic,omitempty"`
	SwingHorizontalModes               []string `json:"swing_horizontal_modes,omitempty"`
	SwingModeCommandTemplate           string   `json:"swing_mode_command_template,omitempty"`
	SwingModeCommandTopic              string   `json:"swing_mode_command_topic,omitempty"`
	SwingModeStateTemplate             string   `json:"swing_mode_state_template,omitempty"`
	SwingModeStateTopic                string   `json:"swing_mode_state_topic,omitempty"`
	SwingModes                         []string `json:"swing_modes,omitempty"`
	TargetHumidityCommandTemplate      string   `json:"target_humidity_command_template,omitempty"`
	TargetHumidityCommandTopic         string   `json:"target_humidity_command_topic,omitempty"`
	TargetHumidityStateTemplate        string   `json:"target_humidity_state_template,omitempty"`
	TargetHumidityStateTopic           string   `json:"target_humidity_state_topic,omitempty"`
	TempStep                           *float64 `json:"temp_step,omitempty"`
	TemperatureCommandTemplate         string   `json:"temperature_command_template,omitempty"`
	TemperatureCommandTopic            string   `json:"temperature_command_topic,omitempty"`
	TemperatureHighCommandTemplate     string   `json:"temperature_high_command_template,omitempty"`
	TemperatureHighCommandTopic        string   `json:"temperature_high_command_topic,omitempty"`
	TemperatureHighStateTemplate       string   `json:"temperature_high_state_template,omitempty"`
	TemperatureHighStateTopic          string   `json:"temperature_high_state_topic,omitempty"`
	TemperatureLowCommandTemplate      string   `json:"temperature_low_command_template,omitempty"`
	TemperatureLowCommandTopic         string   `json:"temperature_low_command_topic,omitempty"`
	TemperatureLowStateTemplate        string   `json:"temperature_low_state_template,omitempty"`
	TemperatureLowStateTopic           string   `json:"temperature_low_state_topic,omitempty"`
	TemperatureStateTemplate           string   `json:"temperature_state_template,omitempty"`
	TemperatureStateTopic              string   `json:"temperature_state_topic,omitempty"`
	TemperatureUnit                    string   `json:"temperature_unit,omitempty"`
}

// CoverFields are the discovery keys platform cover accepts beyond the ones
// [Component] already carries.
type CoverFields struct {
	PayloadClose        string `json:"payload_close,omitempty"`
	PayloadOpen         string `json:"payload_open,omitempty"`
	PayloadStop         string `json:"payload_stop,omitempty"`
	PayloadStopTilt     string `json:"payload_stop_tilt,omitempty"`
	PositionClosed      *int   `json:"position_closed,omitempty"`
	PositionOpen        *int   `json:"position_open,omitempty"`
	PositionTemplate    string `json:"position_template,omitempty"`
	PositionTopic       string `json:"position_topic,omitempty"`
	SetPositionTemplate string `json:"set_position_template,omitempty"`
	SetPositionTopic    string `json:"set_position_topic,omitempty"`
	StateClosed         string `json:"state_closed,omitempty"`
	StateClosing        string `json:"state_closing,omitempty"`
	StateOpen           string `json:"state_open,omitempty"`
	StateOpening        string `json:"state_opening,omitempty"`
	StateStopped        string `json:"state_stopped,omitempty"`
	TiltClosedValue     *int   `json:"tilt_closed_value,omitempty"`
	TiltCommandTemplate string `json:"tilt_command_template,omitempty"`
	TiltCommandTopic    string `json:"tilt_command_topic,omitempty"`
	TiltMax             *int   `json:"tilt_max,omitempty"`
	TiltMin             *int   `json:"tilt_min,omitempty"`
	TiltOpenedValue     *int   `json:"tilt_opened_value,omitempty"`
	TiltOptimistic      *bool  `json:"tilt_optimistic,omitempty"`
	TiltStatusTemplate  string `json:"tilt_status_template,omitempty"`
	TiltStatusTopic     string `json:"tilt_status_topic,omitempty"`
}

// DatetimeFields are the discovery keys platform datetime accepts beyond the ones
// [Component] already carries.
type DatetimeFields struct {
	Timezone string `json:"timezone,omitempty"`
}

// DeviceAutomationFields are the discovery keys platform device_automation accepts beyond the ones
// [Component] already carries.
type DeviceAutomationFields struct {
	AutomationType string `json:"automation_type,omitempty"` // required
}

// DeviceTrackerFields are the discovery keys platform device_tracker accepts beyond the ones
// [Component] already carries.
type DeviceTrackerFields struct {
	PayloadHome    string `json:"payload_home,omitempty"`
	PayloadNotHome string `json:"payload_not_home,omitempty"`
	PayloadReset   string `json:"payload_reset,omitempty"`
	SourceType     string `json:"source_type,omitempty"`
}

// EventFields are the discovery keys platform event accepts beyond the ones
// [Component] already carries.
type EventFields struct {
	EventTypes []string `json:"event_types,omitempty"` // required
}

// FanFields are the discovery keys platform fan accepts beyond the ones
// [Component] already carries.
type FanFields struct {
	DirectionCommandTemplate   string   `json:"direction_command_template,omitempty"`
	DirectionCommandTopic      string   `json:"direction_command_topic,omitempty"`
	DirectionStateTopic        string   `json:"direction_state_topic,omitempty"`
	DirectionValueTemplate     string   `json:"direction_value_template,omitempty"`
	OscillationCommandTemplate string   `json:"oscillation_command_template,omitempty"`
	OscillationCommandTopic    string   `json:"oscillation_command_topic,omitempty"`
	OscillationStateTopic      string   `json:"oscillation_state_topic,omitempty"`
	OscillationValueTemplate   string   `json:"oscillation_value_template,omitempty"`
	PayloadOff                 string   `json:"payload_off,omitempty"`
	PayloadOn                  string   `json:"payload_on,omitempty"`
	PayloadOscillationOff      string   `json:"payload_oscillation_off,omitempty"`
	PayloadOscillationOn       string   `json:"payload_oscillation_on,omitempty"`
	PayloadResetPercentage     string   `json:"payload_reset_percentage,omitempty"`
	PayloadResetPresetMode     string   `json:"payload_reset_preset_mode,omitempty"`
	PercentageCommandTemplate  string   `json:"percentage_command_template,omitempty"`
	PercentageCommandTopic     string   `json:"percentage_command_topic,omitempty"`
	PercentageStateTopic       string   `json:"percentage_state_topic,omitempty"`
	PercentageValueTemplate    string   `json:"percentage_value_template,omitempty"`
	PresetModeCommandTemplate  string   `json:"preset_mode_command_template,omitempty"`
	PresetModeCommandTopic     string   `json:"preset_mode_command_topic,omitempty"`
	PresetModeStateTopic       string   `json:"preset_mode_state_topic,omitempty"`
	PresetModeValueTemplate    string   `json:"preset_mode_value_template,omitempty"`
	PresetModes                []string `json:"preset_modes,omitempty"`
	SpeedRangeMax              *int     `json:"speed_range_max,omitempty"`
	SpeedRangeMin              *int     `json:"speed_range_min,omitempty"`
	StateValueTemplate         string   `json:"state_value_template,omitempty"`
}

// HumidifierFields are the discovery keys platform humidifier accepts beyond the ones
// [Component] already carries.
type HumidifierFields struct {
	ActionTemplate                string   `json:"action_template,omitempty"`
	ActionTopic                   string   `json:"action_topic,omitempty"`
	CurrentHumidityTemplate       string   `json:"current_humidity_template,omitempty"`
	CurrentHumidityTopic          string   `json:"current_humidity_topic,omitempty"`
	MaxHumidity                   *float64 `json:"max_humidity,omitempty"`
	MinHumidity                   *float64 `json:"min_humidity,omitempty"`
	ModeCommandTemplate           string   `json:"mode_command_template,omitempty"`
	ModeCommandTopic              string   `json:"mode_command_topic,omitempty"`
	ModeStateTemplate             string   `json:"mode_state_template,omitempty"`
	ModeStateTopic                string   `json:"mode_state_topic,omitempty"`
	Modes                         []string `json:"modes,omitempty"`
	PayloadOff                    string   `json:"payload_off,omitempty"`
	PayloadOn                     string   `json:"payload_on,omitempty"`
	PayloadResetHumidity          string   `json:"payload_reset_humidity,omitempty"`
	PayloadResetMode              string   `json:"payload_reset_mode,omitempty"`
	StateValueTemplate            string   `json:"state_value_template,omitempty"`
	TargetHumidityCommandTemplate string   `json:"target_humidity_command_template,omitempty"`
	TargetHumidityCommandTopic    string   `json:"target_humidity_command_topic,omitempty"` // required
	TargetHumidityStateTemplate   string   `json:"target_humidity_state_template,omitempty"`
	TargetHumidityStateTopic      string   `json:"target_humidity_state_topic,omitempty"`
}

// ImageFields are the discovery keys platform image accepts beyond the ones
// [Component] already carries.
type ImageFields struct {
	ContentType   string `json:"content_type,omitempty"`
	ImageEncoding string `json:"image_encoding,omitempty"`
	ImageTopic    string `json:"image_topic,omitempty"`
	URLTemplate   string `json:"url_template,omitempty"`
	URLTopic      string `json:"url_topic,omitempty"`
}

// InfraredEmitterFields are the discovery keys platform infrared (schema emitter) accepts beyond the ones
// [Component] already carries.
type InfraredEmitterFields struct {
	Schema string `json:"schema,omitempty"` // required
}

// InfraredReceiverFields are the discovery keys platform infrared (schema receiver) accepts beyond the ones
// [Component] already carries.
type InfraredReceiverFields struct {
	Schema string `json:"schema,omitempty"` // required
}

// LawnMowerFields are the discovery keys platform lawn_mower accepts beyond the ones
// [Component] already carries.
type LawnMowerFields struct {
	ActivityStateTopic         string `json:"activity_state_topic,omitempty"`
	ActivityValueTemplate      string `json:"activity_value_template,omitempty"`
	DockCommandTemplate        string `json:"dock_command_template,omitempty"`
	DockCommandTopic           string `json:"dock_command_topic,omitempty"`
	PauseCommandTemplate       string `json:"pause_command_template,omitempty"`
	PauseCommandTopic          string `json:"pause_command_topic,omitempty"`
	StartMowingCommandTemplate string `json:"start_mowing_command_template,omitempty"`
	StartMowingCommandTopic    string `json:"start_mowing_command_topic,omitempty"`
}

// LightBasicFields are the discovery keys platform light (schema basic) accepts beyond the ones
// [Component] already carries.
type LightBasicFields struct {
	BrightnessCommandTemplate string   `json:"brightness_command_template,omitempty"`
	BrightnessCommandTopic    string   `json:"brightness_command_topic,omitempty"`
	BrightnessScale           *int     `json:"brightness_scale,omitempty"`
	BrightnessStateTopic      string   `json:"brightness_state_topic,omitempty"`
	BrightnessValueTemplate   string   `json:"brightness_value_template,omitempty"`
	ColorModeStateTopic       string   `json:"color_mode_state_topic,omitempty"`
	ColorModeValueTemplate    string   `json:"color_mode_value_template,omitempty"`
	ColorTempCommandTemplate  string   `json:"color_temp_command_template,omitempty"`
	ColorTempCommandTopic     string   `json:"color_temp_command_topic,omitempty"`
	ColorTempKelvin           *bool    `json:"color_temp_kelvin,omitempty"`
	ColorTempStateTopic       string   `json:"color_temp_state_topic,omitempty"`
	ColorTempValueTemplate    string   `json:"color_temp_value_template,omitempty"`
	EffectCommandTemplate     string   `json:"effect_command_template,omitempty"`
	EffectCommandTopic        string   `json:"effect_command_topic,omitempty"`
	EffectList                []string `json:"effect_list,omitempty"`
	EffectStateTopic          string   `json:"effect_state_topic,omitempty"`
	EffectValueTemplate       string   `json:"effect_value_template,omitempty"`
	HSCommandTemplate         string   `json:"hs_command_template,omitempty"`
	HSCommandTopic            string   `json:"hs_command_topic,omitempty"`
	HSStateTopic              string   `json:"hs_state_topic,omitempty"`
	HSValueTemplate           string   `json:"hs_value_template,omitempty"`
	MaxKelvin                 *int     `json:"max_kelvin,omitempty"`
	MaxMireds                 *int     `json:"max_mireds,omitempty"`
	MinKelvin                 *int     `json:"min_kelvin,omitempty"`
	MinMireds                 *int     `json:"min_mireds,omitempty"`
	OnCommandType             string   `json:"on_command_type,omitempty"`
	PayloadOff                string   `json:"payload_off,omitempty"`
	PayloadOn                 string   `json:"payload_on,omitempty"`
	RGBCommandTemplate        string   `json:"rgb_command_template,omitempty"`
	RGBCommandTopic           string   `json:"rgb_command_topic,omitempty"`
	RGBStateTopic             string   `json:"rgb_state_topic,omitempty"`
	RGBValueTemplate          string   `json:"rgb_value_template,omitempty"`
	RGBWCommandTemplate       string   `json:"rgbw_command_template,omitempty"`
	RGBWCommandTopic          string   `json:"rgbw_command_topic,omitempty"`
	RGBWStateTopic            string   `json:"rgbw_state_topic,omitempty"`
	RGBWValueTemplate         string   `json:"rgbw_value_template,omitempty"`
	RGBWWCommandTemplate      string   `json:"rgbww_command_template,omitempty"`
	RGBWWCommandTopic         string   `json:"rgbww_command_topic,omitempty"`
	RGBWWStateTopic           string   `json:"rgbww_state_topic,omitempty"`
	RGBWWValueTemplate        string   `json:"rgbww_value_template,omitempty"`
	Schema                    string   `json:"schema,omitempty"`
	StateValueTemplate        string   `json:"state_value_template,omitempty"`
	WhiteCommandTopic         string   `json:"white_command_topic,omitempty"`
	WhiteScale                *int     `json:"white_scale,omitempty"`
	XYCommandTemplate         string   `json:"xy_command_template,omitempty"`
	XYCommandTopic            string   `json:"xy_command_topic,omitempty"`
	XYStateTopic              string   `json:"xy_state_topic,omitempty"`
	XYValueTemplate           string   `json:"xy_value_template,omitempty"`
}

// LightJSONFields are the discovery keys platform light (schema json) accepts beyond the ones
// [Component] already carries.
type LightJSONFields struct {
	Brightness          *bool    `json:"brightness,omitempty"`
	BrightnessScale     *int     `json:"brightness_scale,omitempty"`
	ColorTempKelvin     *bool    `json:"color_temp_kelvin,omitempty"`
	Effect              *bool    `json:"effect,omitempty"`
	EffectList          []string `json:"effect_list,omitempty"`
	Flash               *bool    `json:"flash,omitempty"`
	FlashTimeLong       *int     `json:"flash_time_long,omitempty"`
	FlashTimeShort      *int     `json:"flash_time_short,omitempty"`
	MaxKelvin           *int     `json:"max_kelvin,omitempty"`
	MaxMireds           *int     `json:"max_mireds,omitempty"`
	MinKelvin           *int     `json:"min_kelvin,omitempty"`
	MinMireds           *int     `json:"min_mireds,omitempty"`
	Schema              string   `json:"schema,omitempty"`
	SupportedColorModes []string `json:"supported_color_modes,omitempty"`
	Transition          *bool    `json:"transition,omitempty"`
	WhiteScale          *int     `json:"white_scale,omitempty"`
}

// LightTemplateFields are the discovery keys platform light (schema template) accepts beyond the ones
// [Component] already carries.
type LightTemplateFields struct {
	BlueTemplate       string   `json:"blue_template,omitempty"`
	BrightnessTemplate string   `json:"brightness_template,omitempty"`
	ColorTempKelvin    *bool    `json:"color_temp_kelvin,omitempty"`
	ColorTempTemplate  string   `json:"color_temp_template,omitempty"`
	CommandOffTemplate string   `json:"command_off_template,omitempty"` // required
	CommandOnTemplate  string   `json:"command_on_template,omitempty"`  // required
	EffectList         []string `json:"effect_list,omitempty"`
	EffectTemplate     string   `json:"effect_template,omitempty"`
	GreenTemplate      string   `json:"green_template,omitempty"`
	MaxKelvin          *int     `json:"max_kelvin,omitempty"`
	MaxMireds          *int     `json:"max_mireds,omitempty"`
	MinKelvin          *int     `json:"min_kelvin,omitempty"`
	MinMireds          *int     `json:"min_mireds,omitempty"`
	RedTemplate        string   `json:"red_template,omitempty"`
	Schema             string   `json:"schema,omitempty"`
	StateTemplate      string   `json:"state_template,omitempty"`
}

// LockFields are the discovery keys platform lock accepts beyond the ones
// [Component] already carries.
type LockFields struct {
	CodeFormat     string `json:"code_format,omitempty"`
	PayloadLock    string `json:"payload_lock,omitempty"`
	PayloadOpen    string `json:"payload_open,omitempty"`
	PayloadReset   string `json:"payload_reset,omitempty"`
	PayloadUnlock  string `json:"payload_unlock,omitempty"`
	StateJammed    string `json:"state_jammed,omitempty"`
	StateLocked    string `json:"state_locked,omitempty"`
	StateLocking   string `json:"state_locking,omitempty"`
	StateOpen      string `json:"state_open,omitempty"`
	StateOpening   string `json:"state_opening,omitempty"`
	StateUnlocked  string `json:"state_unlocked,omitempty"`
	StateUnlocking string `json:"state_unlocking,omitempty"`
}

// NumberFields are the discovery keys platform number accepts beyond the ones
// [Component] already carries.
type NumberFields struct {
	Mode         string `json:"mode,omitempty"`
	PayloadReset string `json:"payload_reset,omitempty"`
}

// SceneFields are the discovery keys platform scene accepts beyond the ones
// [Component] already carries.
type SceneFields struct {
	PayloadOn string `json:"payload_on,omitempty"`
}

// SensorFields are the discovery keys platform sensor accepts beyond the ones
// [Component] already carries.
type SensorFields struct {
	ExpireAfter            *int   `json:"expire_after,omitempty"`
	ForceUpdate            *bool  `json:"force_update,omitempty"`
	LastResetValueTemplate string `json:"last_reset_value_template,omitempty"`
}

// SirenFields are the discovery keys platform siren accepts beyond the ones
// [Component] already carries.
type SirenFields struct {
	AvailableTones     []string `json:"available_tones,omitempty"`
	CommandOffTemplate string   `json:"command_off_template,omitempty"`
	PayloadOff         string   `json:"payload_off,omitempty"`
	PayloadOn          string   `json:"payload_on,omitempty"`
	StateOff           string   `json:"state_off,omitempty"`
	StateOn            string   `json:"state_on,omitempty"`
	StateValueTemplate string   `json:"state_value_template,omitempty"`
	SupportDuration    *bool    `json:"support_duration,omitempty"`
	SupportVolumeSet   *bool    `json:"support_volume_set,omitempty"`
}

// SwitchFields are the discovery keys platform switch accepts beyond the ones
// [Component] already carries.
type SwitchFields struct {
	PayloadOff string `json:"payload_off,omitempty"`
	PayloadOn  string `json:"payload_on,omitempty"`
	StateOff   string `json:"state_off,omitempty"`
	StateOn    string `json:"state_on,omitempty"`
}

// TagFields are the discovery keys platform tag accepts beyond the ones
// [Component] already carries.
type TagFields struct {
	Topic string `json:"topic,omitempty"` // required
}

// TextFields are the discovery keys platform text accepts beyond the ones
// [Component] already carries.
type TextFields struct {
	Mode    string `json:"mode,omitempty"`
	Pattern string `json:"pattern,omitempty"`
}

// UpdateFields are the discovery keys platform update accepts beyond the ones
// [Component] already carries.
type UpdateFields struct {
	DisplayPrecision      *int   `json:"display_precision,omitempty"`
	LatestVersionTemplate string `json:"latest_version_template,omitempty"`
	LatestVersionTopic    string `json:"latest_version_topic,omitempty"`
	PayloadInstall        string `json:"payload_install,omitempty"`
	ReleaseSummary        string `json:"release_summary,omitempty"`
	ReleaseURL            string `json:"release_url,omitempty"`
	Title                 string `json:"title,omitempty"`
}

// VacuumFields are the discovery keys platform vacuum accepts beyond the ones
// [Component] already carries.
type VacuumFields struct {
	CleanSegmentsCommandTemplate string   `json:"clean_segments_command_template,omitempty"`
	CleanSegmentsCommandTopic    string   `json:"clean_segments_command_topic,omitempty"`
	FanSpeedList                 []string `json:"fan_speed_list,omitempty"`
	PayloadCleanSpot             string   `json:"payload_clean_spot,omitempty"`
	PayloadLocate                string   `json:"payload_locate,omitempty"`
	PayloadPause                 string   `json:"payload_pause,omitempty"`
	PayloadReturnToBase          string   `json:"payload_return_to_base,omitempty"`
	PayloadStart                 string   `json:"payload_start,omitempty"`
	PayloadStop                  string   `json:"payload_stop,omitempty"`
	SendCommandTopic             string   `json:"send_command_topic,omitempty"`
	SetFanSpeedTopic             string   `json:"set_fan_speed_topic,omitempty"`
	SupportedFeatures            []string `json:"supported_features,omitempty"`
}

// ValveFields are the discovery keys platform valve accepts beyond the ones
// [Component] already carries.
type ValveFields struct {
	PayloadClose    string `json:"payload_close,omitempty"`
	PayloadOpen     string `json:"payload_open,omitempty"`
	PayloadStop     string `json:"payload_stop,omitempty"`
	PositionClosed  *int   `json:"position_closed,omitempty"`
	PositionOpen    *int   `json:"position_open,omitempty"`
	ReportsPosition *bool  `json:"reports_position,omitempty"`
	StateClosed     string `json:"state_closed,omitempty"`
	StateClosing    string `json:"state_closing,omitempty"`
	StateOpen       string `json:"state_open,omitempty"`
	StateOpening    string `json:"state_opening,omitempty"`
}

// WaterHeaterFields are the discovery keys platform water_heater accepts beyond the ones
// [Component] already carries.
type WaterHeaterFields struct {
	CurrentTemperatureTemplate string   `json:"current_temperature_template,omitempty"`
	CurrentTemperatureTopic    string   `json:"current_temperature_topic,omitempty"`
	Initial                    *float64 `json:"initial,omitempty"`
	MaxTemp                    *float64 `json:"max_temp,omitempty"`
	MinTemp                    *float64 `json:"min_temp,omitempty"`
	ModeCommandTemplate        string   `json:"mode_command_template,omitempty"`
	ModeCommandTopic           string   `json:"mode_command_topic,omitempty"`
	ModeStateTemplate          string   `json:"mode_state_template,omitempty"`
	ModeStateTopic             string   `json:"mode_state_topic,omitempty"`
	Modes                      []string `json:"modes,omitempty"`
	PayloadOff                 string   `json:"payload_off,omitempty"`
	PayloadOn                  string   `json:"payload_on,omitempty"`
	PowerCommandTemplate       string   `json:"power_command_template,omitempty"`
	PowerCommandTopic          string   `json:"power_command_topic,omitempty"`
	Precision                  *float64 `json:"precision,omitempty"`
	TemperatureCommandTemplate string   `json:"temperature_command_template,omitempty"`
	TemperatureCommandTopic    string   `json:"temperature_command_topic,omitempty"`
	TemperatureStateTemplate   string   `json:"temperature_state_template,omitempty"`
	TemperatureStateTopic      string   `json:"temperature_state_topic,omitempty"`
	TemperatureUnit            string   `json:"temperature_unit,omitempty"`
}

// FieldsIndex maps a platform — "<platform>", or "<platform>/<variant>" for
// the two platforms that dispatch on a payload key — to a zero value of the
// Fields struct carrying that platform's own discovery keys.
//
// It exists so nothing has to hand-maintain a switch from a platform to its
// struct: this package's validating test walks it, and a consumer can use it
// to find the type it should be filling in.
var FieldsIndex = map[string]any{
	"alarm_control_panel": AlarmControlPanelFields{},
	"binary_sensor":       BinarySensorFields{},
	"button":              ButtonFields{},
	"camera":              CameraFields{},
	"climate":             ClimateFields{},
	"cover":               CoverFields{},
	"datetime":            DatetimeFields{},
	"device_automation":   DeviceAutomationFields{},
	"device_tracker":      DeviceTrackerFields{},
	"event":               EventFields{},
	"fan":                 FanFields{},
	"humidifier":          HumidifierFields{},
	"image":               ImageFields{},
	"infrared/emitter":    InfraredEmitterFields{},
	"infrared/receiver":   InfraredReceiverFields{},
	"lawn_mower":          LawnMowerFields{},
	"light/basic":         LightBasicFields{},
	"light/json":          LightJSONFields{},
	"light/template":      LightTemplateFields{},
	"lock":                LockFields{},
	"number":              NumberFields{},
	"scene":               SceneFields{},
	"sensor":              SensorFields{},
	"siren":               SirenFields{},
	"switch":              SwitchFields{},
	"tag":                 TagFields{},
	"text":                TextFields{},
	"update":              UpdateFields{},
	"vacuum":              VacuumFields{},
	"valve":               ValveFields{},
	"water_heater":        WaterHeaterFields{},
}

// No Fields struct is generated for date, notify, select, time: every key those
// platforms accept is already declared on [Component].
